name: Build and Upload Chrome Extension

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Zip the extension files
      - name: Zip extension
        run: |
          zip -r add-words-to-anki.zip . -x .git/\* .github/\* README.md
        shell: bash

      # Step 3: Upload the zipped extension as an artifact
      - name: Upload extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: add-words-to-anki
          path: add-words-to-anki.zip